name: 'test'

on: 'push'

jobs:
  test:
    runs-on: 'ubuntu-latest'
    container:
      image: 'maven:3.6-openjdk-11'
    steps:
      - uses: 'actions/checkout@v2'
      - run: 'mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V'
      - run: 'mvn test -B'

