name: 'test'

on: 'push'

jobs:
  test:
    container:
      image: 'maven:3.6-openjdk-11'
    steps:
      - name: 'before_script'
        run: 'mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V'
      - name: 'script'
        run: 'mvn test -B'

